# action.yml
name: 'Swift Build Lambda'
description: 'Builds and packages an AWS Lambda written in Swift.'
inputs:
  executable:
    description: 'Name of executable'
    required: true
  architecture:
    description: 'The platform this Lambda should be built for. (x86_64 or arm64).'
    required: false
    default: 'x86_64'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.executable }}
branding:
  icon: 'code'
  color: 'orange'